### ISSUE TITLE
OS default theme is a little bit weird

### ISSUE THREAD

**Issue by samchon** [JulianWowra/typedoc-github-theme#1]
## OS Mode

<img width="627" alt="image" src="https://github.com/user-attachments/assets/1b7be053-4d7a-4b32-8aa8-6e08abfa13b1">

## Light Mode

<img width="626" alt="image" src="https://github.com/user-attachments/assets/02c64457-e8e1-4954-8349-e6df5f461e8e">

## Dark Mode

<img width="629" alt="image" src="https://github.com/user-attachments/assets/edff8fb9-d733-42ff-9a61-d4c341a5026e">

**Comment by JulianWowra** [comment]
Hello, thank you for your issue.

I can see two differences in the pictures.
- Scrollbar color
- Different colors in the code block

You are right, the standard code block is not optimal in terms of colors. Do you see any other problems or is the issue related to this one?

Thank you, best regards Julian

**Comment by JulianWowra** [comment]
Hey @samchon,
a [new version](https://github.com/KillerJulian/typedoc-github-theme/releases/tag/v0.1.2) was released 🚀
Please check if your problem still exists and if it does, please send me new information. 

Best regards
Julian

---

_By the way:
It is sufficient if you now only specify the plugin as a TypeDoc option. The theme will be set automatically._

**Comment by JulianWowra** [comment]
Closed because no answer.  
Please open again if the bug still persists
