### ISSUE TITLE
Show an example

### ISSUE THREAD

**Issue by HarelM** [JulianWowra/typedoc-github-theme#2]
It is unclear how this theme would look, I would advise to either have a sample project generate typedoc site with this theme and present it in the github pages or add a screenshot to the readme.
Thanks!

**Comment by JulianWowra** [comment]
Oh yes, you're right. It's already in the works! I'm gradually converting my Github projects to this theme. After that I will provide a more comprehensive example.

Maybe that will inspire you in time?

[![Issue #1](https://private-user-images.githubusercontent.com/13158709/353788610-edff8fb9-d733-42ff-9a61-d4c341a5026e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NzIyMjAsIm5iZiI6MTcyMjY3MTkyMCwicGF0aCI6Ii8xMzE1ODcwOS8zNTM3ODg2MTAtZWRmZjhmYjktZDczMy00MmZmLTlhNjEtZDRjMzQxYTUwMjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA3NTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNjkyYTM3Nzg1YjQyZTAzNzRjZDNkMzdjODY1Y2VjZWNjMDQ4YmY0MWJjYWRkODFkZmRmOTk0ZjA5N2FmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._KBMMKorUDtT8-qkZwys5rNTHGDoPtf9pNi4whbzTMk)](https://github.com/KillerJulian/typedoc-github-theme/issues/1)

Thank you, best regards Julian
