### ISSUE TITLE
support for alerts / asides

### ISSUE THREAD

**Issue by boneskull** [JulianWowra/typedoc-github-theme#3]
Hi, thank you for this theme. 

While it seems to have gone under the radar, [alerts are a thing in GFM](https://github.com/orgs/community/discussions/16925).  Is that something this project would want to support?  

If you're interested in adding this, I may try to do it myself; I'll send a PR if I'm successful.

**Comment by JulianWowra** [comment]
Hello, thank you for this idea.

Since GitHub supports this syntax, I would be inspired to include it in this TypeDoc theme as well. Feel free to try your hand at this task, I will then view your pull request. Let me know if you need help :)

**Comment by JulianWowra** [comment]
@boneskull What is the current status of your task?

**Comment by JulianWowra** [comment]
Typedoc now supports the desired feature. The feature has been adapted to the Github theme in the current release
